import pandas as pd

df = pd.read_csv("quiz1_weather.csv")
print(df.shape)
print(df.columns)
print(df.head(5))
print(df[0:5])
print(df.tail(5))
print(df[['day','temperature']])
print(df['temperature'].max())
print(df['temperature'].min())
print(df['temperature'].mean())
print(df['windspeed'].mean())
print(df['temperature'].median())
print(df['windspeed'].median())
print(df.sort_values(["state"],ascending=False))
df=df.drop(df.index[0])
df=df.drop(df.index[0])
df=df.drop(df.index[0])
df=df.fillna("1234")
print(df)
